/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface ColumnCommonProps {
  /**
   * 列标题
   */
  label?: string;
  /**
   * 列标题的内容属性名称
   */
  prop?: string;
  /**
   * 对应列的宽度
   */
  width?: string;
  /**
   * 深结构数据绑定值
   */
  bind?: string;
  /**
   * 对应列的最小宽度，与 width 的区别是 width 是固定的，minWidth 会把剩余宽度按比例分配给设置了 minWidth 的列
   */
  minWidth?: string;
  /**
   * 列是否固定在左侧或者右侧，true 表示固定在左侧
   */
  fixed?: "left" | "right";
  /**
   * 列的单元格自定义类名
   */
  className?: string;
  /**
   * 列标题的自定义类名
   */
  labelClassName?: string;
  /**
   * 对应列是否可以排序，如果设置为 'custom'，则代表用户希望远程排序，需要监听 Table 的 sort-change 事件
   */
  sortable?: true | false | "custom";
  /**
   * 用来格式化列内容
   */
  formatter?: (row, value, column) => {};
  /**
   * 当内容过长被隐藏时显示 tooltip
   * @default false
   */
  overHidden?: boolean;
  /**
   * 对齐方式
   */
  align?: "left" | "center" | "right";
  /**
   * 表头对齐方式，若不设置该项，则使用表格的对齐方式
   */
  headerAlign?: "left" | "center" | "right";
  /**
   * 数据过滤的选项。
   * @default false
   */
  filters?: boolean;
  /**
   * 是否为搜索项
   * @default false
   */
  search?: boolean;
  /**
   * 搜索项初始化值
   */
  searchValue?: string;
  /**
   * 搜索项辅助文字
   */
  searchPlaceholder?: string;
  /**
   * 搜索项框栅列
   * @default 8
   */
  searchSpan?: number;
  /**
   * 搜索项位置排序，序号越大越靠前
   */
  searchOrder?: number;
  /**
   * 搜索项框间距
   */
  searchGutter?: number;
  /**
   * 搜索项为范围搜索
   * @default false
   */
  searchRange?: boolean;
  /**
   * 搜索项的类型
   */
  searchType?: string;
  /**
   * 搜索项标题宽度
   * @default 80
   */
  searchLabelWidth?: number;
  /**
   * 搜索项清除
   * @default false
   */
  searchClearable?: boolean;
  /**
   * 搜索项是否多选
   * @default false
   */
  searchMultiple?: boolean;
  /**
   * 搜索项将选中值按文字的形式展示
   * @default false
   */
  searchTags?: boolean;
  /**
   * 搜索项标题位置
   */
  searchLabelPosition?: "left" | "right" | "top";
  /**
   * 弹出表单是否显示
   * @default true
   */
  display?: boolean;
  /**
   * 弹出表单是否禁止
   * @default false
   */
  disabled?: boolean;
  /**
   * 表单新增时项是否禁止
   * @default false
   */
  addDisabled?: boolean;
  /**
   * 表单编辑时项是否禁止
   * @default false
   */
  editDisabled?: boolean;
  /**
   * 表单查看时项是否禁止
   * @default false
   */
  viewDisabled?: boolean;
  /**
   * 表单新增时项是否显示
   * @default true
   */
  addDisplay?: boolean;
  /**
   * 表单编辑时项是否显示
   * @default true
   */
  editDisplay?: boolean;
  /**
   * 表单查看时项是否显示
   * @default true
   */
  viewDisplay?: boolean;
  /**
   * 对应列是否可以通过拖动改变宽度（需要在option中border属性为真）
   * @default true
   */
  resizable?: boolean;
  [k: string]: unknown;
}
