/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Props {
    /**
     * 选项标签为选项对象的某个属性值
     * @default label
     */
    label?: string;
    /**
     * 选项的值为选项对象的某个属性值
     * @default value
     */
    value?: string;
    /**
     * 选项的子选项为选项对象的某个属性值
     * @default children
     */
    children?: string;
    /**
     * 选项的禁用为选项对象的某个属性值
     * @default disabled
     */
    disabled?: string;
    /**
     * 选项返回结构的层级(例如data.data)
     */
    res?: string;
    [k: string]: unknown;
}
